from setuptools import setup, find_packages

setup(
    name="transition_uncertainty",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        "jax==0.4.23",
        "jaxlib==0.4.23",
        "dill==0.3.7",
        "joblib==1.4.2",
        "torch==1.13.1",
        "matplotlib==3.8.2",
        "numpy==1.26.3",
        "pandas==2.1.4",
        "pingouin==0.5.3",
        "seaborn==0.13.1",
        "statsmodels==0.14.1",
        "scikit-learn==1.3.2",
        "scipy==1.12.0",
        "dill==0.3.7",
        "arviz==0.17.0",
        "numpyro==0.13.2",
        "bambi==0.13.0",
        "requests==2.31.0",
        "facsimile @ git+https://github.com/the-wise-lab/FACSIMILE.git#egg=facsimile",
        "model_fit_tools @ git+https://github.com/the-wise-lab/model-fit-tools.git#egg=model_fit_tools",
        "stats_utils @ git+https://github.com/the-wise-lab/stats-utils.git#egg=stats_utils",
        "bayesflow @ git+https://github.com/bayesflow-org/bayesflow@dev#egg=bayesflow",
        "behavioural_modelling @ git+https://github.com/tobywise/behavioural-modelling.git#egg=behavioural_modelling",
    ],
    url="https://github.com/the-wise-lab/transition-learning-public",
    license="MIT",
)
